In [1]:
import numpy as np
from __future__ import division

# #1

In [2]:
v0 = np.array([0.5, 0.5, 0.5, 0.5])
v1 = np.array([0.5, 0.5, -0.5, -0.5])

In [3]:
v0.dot(v1)

0.0

# #2

In [4]:
v2 = np.array([0.5, -0.5, 0.5, -0.5])

In [5]:
v3 = -(v0 + v1 + v2)

In [6]:
v3

array([-1.5, -0.5, -0.5,  0.5])

In [7]:
v0 + v1 + v2 + v3

array([ 0.,  0.,  0.,  0.])

In [ ]:
v3 = np.array()

Only this v3 can satisfy 

    (v0 + v1 + v2 + v3) = 0

In [26]:
for a in range(-10, 11):
    for b in range(-10, 11):
        for c in range(-10, 11):
            for d in range(-10, 11):
                v3 = np.array([a/2, b/2, c/2, d/2])
                #t1 = v3.dot(v3) == 1
                t2 = v3.dot(v0) == 0
                t3 = v3.dot(v1) == 0
                t4 = v3.dot(v2) == 0
                if t2 and t3 and t4:
                    print "found", a/2, b/2, c/2, d/2
                

found -5.0 5.0 5.0 -5.0
found -4.5 4.5 4.5 -4.5
found -4.0 4.0 4.0 -4.0
found -3.5 3.5 3.5 -3.5
found -3.0 3.0 3.0 -3.0
found -2.5 2.5 2.5 -2.5
found -2.0 2.0 2.0 -2.0
found -1.5 1.5 1.5 -1.5
found -1.0 1.0 1.0 -1.0
found -0.5 0.5 0.5 -0.5
found 0.0 0.0 0.0 0.0
found 0.5 -0.5 -0.5 0.5
found 1.0 -1.0 -1.0 1.0
found 1.5 -1.5 -1.5 1.5
found 2.0 -2.0 -2.0 2.0
found 2.5 -2.5 -2.5 2.5
found 3.0 -3.0 -3.0 3.0
found 3.5 -3.5 -3.5 3.5
found 4.0 -4.0 -4.0 4.0
found 4.5 -4.5 -4.5 4.5
found 5.0 -5.0 -5.0 5.0


In [9]:
v3 = np.array([0.5, -0.5, -0.5, 0.5])

# #3

In [10]:
y = np.array([21, 1, 0, -1])

In [11]:
for a in range(-10, 11):
    for b in range(-10, 11):
        for c in range(-10, 11):
            for d in range(-10, 11):
                y0 = a * v0 + b * v1 + c * v2 + d * v3
                if np.array_equal(y, y0):
                    print "found it", a, b, c, d

found it 1 2 1 0


In [12]:
a = 1
b = 2
c = 1
d = 0
a * v0 + b * v1 + c * v2 + d * v3

array([ 2.,  1.,  0., -1.])

# #4

In [13]:
y + v0 + v1 + v3

array([ 3.5,  1.5, -0.5, -0.5])

In [14]:
y + (v1 + v2) + v2 + v3

array([ 4.,  0.,  0., -2.])

In [15]:
y + v0 + v2 + v3

array([ 3.5,  0.5,  0.5, -0.5])

In [23]:
print(v0)
print(v1)
print(v2)
print(v3)
print(y)
print(v3 - 2 * v1)

[ 0.5  0.5  0.5  0.5]
[ 0.5  0.5 -0.5 -0.5]
[ 0.5 -0.5  0.5 -0.5]
[ 0.5 -0.5 -0.5  0.5]
[ 2  1  0 -1]
[-0.5 -1.5  0.5  1.5]


In [16]:
y + v0 + v1 + v2

array([ 3.5,  1.5,  0.5, -1.5])

# #5

In [17]:
x = np.array([0, 1, 2])

In [18]:
x + np.array([-2, -0, -1])

array([-2,  1,  1])

In [19]:
F = np.array([[1,0,-1],
              [-1,1,0],
              [0,-1,1],
             ])
F.dot(x)

array([-2,  1,  1])

# #6

In [20]:
A = np.array([
    [0,0,0,1],
    [1,0,0,0],
    [0,1,0,0],
    [0,0,1,0],
])

In [21]:
A.dot(A).dot(A).dot(A)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])