In [98]:
import numpy as np
from __future__ import division

# #1

In [6]:
v0 = np.array([0.5, 0.5, 0.5, 0.5])
v1 = np.array([0.5, 0.5, -0.5, -0.5])

In [7]:
v0.dot(v1)

0.0

# #2

In [8]:
v2 = np.array([0.5, -0.5, 0.5, -0.5])

In [10]:
v3 = -(v0 + v1 + v2)

In [13]:
v3

array([-1.5, -0.5, -0.5,  0.5])

In [14]:
v0 + v1 + v2 + v3

array([ 0.,  0.,  0.,  0.])

Only this v3 can satisfy 

    (v0 + v1 + v2 + v3) = 0

In [101]:
for a in range(-10, 11):
    for b in range(-10, 11):
        for c in range(-10, 11):
            for d in range(-10, 11):
                v3 = np.array([a/2, b/2, c/2, d/2])
                t1 = v3.dot(v3) == 1
                t2 = v3.dot(v0) == 0
                t3 = v3.dot(v1) == 0
                t4 = v3.dot(v2) == 0
                if t1 and t2 and t3 and t4:
                    print "found", a/2, b/2, c/2, d/2
                

found -0.5 0.5 0.5 -0.5
found 0.5 -0.5 -0.5 0.5


In [103]:
v3 = np.array([-0.5, 0.5, 0.5, -0.5])

# #3

In [104]:
y = np.array([2, 1, 0, -1])

In [107]:
for a in range(-10, 11):
    for b in range(-10, 11):
        for c in range(-10, 11):
            for d in range(-10, 11):
                y0 = a * v0 + b * v1 + c * v2 + d * v3
                if np.array_equal(y, y0):
                    print "found it", a, b, c, d

found it 1 2 1 0


In [106]:
a = 1
b = 2
c = 1
d = 0
a * v0 + b * v1 + c * v2 + d * v3

array([ 2.,  1.,  0., -1.])

# #4

In [52]:
y + v0 + v1 + v3

array([ 1.5,  1.5, -0.5, -0.5])

In [53]:
y + (v1 + v2) + v2 + v3

array([ 2.,  0.,  0., -2.])

In [54]:
y + v0 + v2 + v3

array([ 1.5,  0.5,  0.5, -0.5])

In [55]:
y + v0 + v1 + v2

array([ 3.5,  1.5,  0.5, -1.5])

# #5

In [62]:
x = np.array([0, 1, 2])

In [64]:
x + np.array([-2, -0, -1])

array([-2,  1,  1])

In [66]:
D = np.array([[1,0,-1],
              [-1,1,0],
              [0,-1,1],
             ])
D.dot(x)

array([-2,  1,  1])

# #6

In [67]:
A = np.array([
    [0,0,0,1],
    [1,0,0,0],
    [0,1,0,0],
    [0,0,1,0],
])

In [69]:
A.dot(A).dot(A).dot(A)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])